name: Tests
on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: Pester
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Pester tests
        shell: pwsh
        run: |
          . .\tests\PesterConfiguration.ps1
          Invoke-Pester -Configuration $PesterConfiguration